services:
  prometheus:
    image: prom/prometheus:latest
    container_name: speciesnet-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: speciesnet-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus